# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [4]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(3, 5)
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [6]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [7]:
print(B-C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]


In [8]:
print(B*C)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [9]:
print(B@C)

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [5]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
exponent_B = np.exp(B) # e is the base, natural logarithm
print(exponent_B)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [15]:
min_value_matrix = np.min(B)
print(min_value_matrix)

1


In [19]:
min_value_row = np.min(B, axis=1)   #axis=1 is for rows column-wise, axis=0 is for columns row-wise
print(min_value_row)

[1 4 7]


In [21]:
min_value_column = np.min(B, axis=0)
print(min_value_column)

[1 2 3]


In [23]:
min_value_index = np.argmin(B)
print(f"minimum index value:[{min_value_index}]")

minimum index value:[0]


In [7]:
min_index_row = np.argmin(B, axis=1)                         
print(f"minimum index value in each row:[{min_index_row}]")

minimum index value in each row:[[0 0 0]]


In [25]:
np.sum(B)

45

In [9]:
np.mean(B, axis=0)

array([4., 5., 6.])

In [50]:
np.median(B, axis=0)

array([4., 5., 6.])

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [31]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [37]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

It means executing a partial slicing or can be considered complete slices when providing fewer indices than axes when slicing.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [41]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [47]:
for i in A:                      # for i-rows in matrix A
    for elements in i:           # for each elements contained in i-rows
        print(elements)
        print()

1

2

3

4

5

6

7

8

9

10

11

12

13

14

15



### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [60]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [59]:
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
d = c.reshape(2,3,-1)
print(d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


b = a.reshape(axis_0, axis_1, axis_2)
b = a.reshape(  2   ,   3   ,  -1   )

I thought first that axis_0 always mean columns and axis_1 is for rows in a matrix while axis_2 is unexplored.

in this scenario, axis_0 means number of blocks in the matrix which gives us:
 [[ 1  2]
  [ 3  4]
  [ 5  6]]
as the first block
and
 [[ 7  8]
  [ 9 10]
  [11 12]]
as the second block

axis_1 is still for rows but in this case its for "rows in each block", makes sense we see 3 rows in each block.

axis_2. The value inputted in axis_2 "-1" as one of the dimensions, indicate Numpy to calculate the size of the dimension in b so that the toal number of elemends remains the same.

The calculating process of axis_2 is following: total number of elements in b / axis_0*axis_1 ---> which makes 12 / 2*3 = 2
Thus, it gives us a.reshape(2, 3, -1) ---> a.reshape(2, 3, 2)

b has therefore 3 axes, which is: 2, 3 and 2


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [64]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)                   #broadcasting will make m2 to match the shape of m1, thus giving us m2 =[ [1,1], [1,1] ]

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [65]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [71]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 1])
print(b)
print()
sum1 = A + b
print(sum1)                               #broadcasting will make b to match the shape of A

[[1 2]
 [3 4]]
[2 1]

[[3 3]
 [5 5]]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [2]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print()
print(B)
print()
print(C)
print()
print(D)
print()
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]

[[ 4 -2  1]
 [ 2 -4 -2]]

[[1 2]
 [2 1]]

[[3 4]
 [4 3]]

[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [11]:
def add_mult_matrices(matrix_1, matrix_2, math_operation):
    
    if not (isinstance(matrix_1, np.ndarray) and isinstance(matrix_2, np.ndarray)):
            raise ValueError("matrices must be Numpy array")
    
    if not math_operation in ("add", "multiply"):
            raise ValueError("math operations should be add or multiply")
    
    if math_operation == "add":
            if matrix_1.shape != matrix_2.shape:
                raise ValueError("both matrix must be in same size to add")
            return matrix_1 + matrix_2
            
    elif math_operation == "multiply":
            if not matrix_1.shape[1] == matrix_2.shape[0]:
                raise ValueError("number of columns in first matrix is not equal to number of rows in second matrix")
            return matrix_1@matrix_2
    

In [182]:
print(add_mult_matrices(-2*A,B,"add"))
print()
print(add_mult_matrices(C,D,"multiply"))
print()
print(add_mult_matrices(C,B,"multiply"))

[[ 0 -4  3]
 [ 0 -2 -4]]

[[11 10]
 [10 11]]

[[  8 -10  -3]
 [ 10  -8   0]]


**Chap2. Question 2**

In [12]:

A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

AB = add_mult_matrices(A, B, "multiply")
AC = add_mult_matrices(A, C, "multiply")

print(AB)
print()
print(AC)
print()
print(AB==AC)
print()
print(B!=C)

print((AB==AC).all())
print((B==C).all())

[[ 4  7]
 [ 8 14]]

[[ 4  7]
 [ 8 14]]

[[ True  True]
 [ True  True]]

[[ True  True]
 [ True  True]]
True
False


**Chap2. Question 3**

In [15]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0 ,4]])
AD = add_mult_matrices(A, D, "multiply")
DA = add_mult_matrices(D, A, "multiply")
print("AD:", AD)
print()
print("DA:", DA)

AD: [[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]

DA: [[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.8, exercise 2**

In [11]:
I = np.array([[1, -1], [-1, 1]])
J = np.array([[-1, 1], [1, -1]])

IJ = add_mult_matrices(I, J, "multiply")
print(IJ)


[[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [17]:
def invert_matrice(matrix_1): # only square matrices may have inverse and an inverse exist when determinant is not 0
    determinant = np.linalg.det(matrix_1)
    if determinant == 0:
        raise ValueError("the matrix is not invertible")
           
    else:
        return np.linalg.inv(matrix_1)
    

In [18]:
K = np.array([[5, 6], [4, 5]])
G = np.array([[6, 4], [3, 3]])
inverse1 = invert_matrice(K)
inverse2 = invert_matrice(G)

In [21]:
print(inverse1)
print(K@inverse1)

print(np.allclose(K @inverse1, np.eye(2)))

[[ 5. -6.]
 [-4.  5.]]
[[ 1.00000000e+00  0.00000000e+00]
 [-3.55271368e-15  1.00000000e+00]]
True


In [22]:
print(6*inverse2)

print(G@inverse2)

print(np.allclose(G @inverse2, np.eye(2)))

[[ 3. -4.]
 [-3.  6.]]
[[1. 0.]
 [0. 1.]]
True


**Quiz p.15, exercise 3**

In [23]:
Å = np.array([[2, 2], [1, 2]])

inverse_Å = invert_matrice(Å)
print(2*inverse_Å)

print(Å@inverse_Å)

print(np.allclose(Å @inverse_Å, np.eye(2)))

[[ 2. -2.]
 [-1.  2.]]
[[1. 0.]
 [0. 1.]]
True


**Chap10. Question 1 a)**

In [31]:
def Gauss_elim(matrix1, matrix2):
    solution = np.linalg.solve(matrix1, matrix2)
    x1 = round(solution[0],)
    x2 = round(solution[1],)
    x3 = round(solution[2],)
    print(f"x1:{x1}  x2:{x2}  x3:{x3}")
    print(matrix1 @ solution)


In [32]:
L = np.array([[3, -7, -2], 
              [-3, 5, 1], 
              [6, -4, 0]])

O = np.array([-7, 5, 2])

Gauss_elim(L,O)


x1:3  x2:4  x3:-6
[-7.  5.  2.]


**Chap10. Question 1 b)**

In [33]:
P = np.array([[1, -2, 3], 
              [-1, 3, -1], 
              [2, -5, 5]])

Y = np.array([1, -1, 1])
Gauss_elim(P,Y)


x1:8  x2:2  x3:-1
[ 1. -1.  1.]


**Chap 12. Question 1**

In [36]:
H = np.array([[3, -7, -2], 
              [-3, 5, 1], 
              [6, -4, 0]])
F = invert_matrice(H)
print(F)
print(np.allclose(H @ F, np.eye(3)))

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]
True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [75]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [76]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [77]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


basic indexing creates a view, which means the data can be changed from the view. in this case we have v2 is a view of v1. if we change v2[-1] = 123 then we also change v1 in the process.

a copy doesnt change the original data and its not a "view" of the other. if v2 would be a copy then its a "copy" of v1 and changes in v2 wont change the data in v1, it will only change v2.

we also see that v1.base returns "none" which means its a copy from the original array while v2.base returns an array of a view from the original v1.
